services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "${EXPOSE_PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - remote-file-network
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_EXPOSE_PORT}:${DB_PORT}"
    networks:
      -  remote-file-network
    volumes:
      - ./my-db:/var/lib/mysql
networks:
  remote-file-network:
